package enums;

public enum TerminErstellenStatus {
	ERSTELLEN,
	TITEL,
	START_DATUM,
	END_DATUM,
	START_ZEIT,
	END_ZEIT,
	ORT_EINGEBEN,
	ATTACHEMENT_EINFÜGEN,
	WIEDERKEHRENDER_TERMIN,
	PERSON_EINLADEN,
	REMINDER_SETZEN,
	TERMIN_SPEICHERN
}
